on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CI: true
    steps:
      - name: checkout main
        uses: actions/checkout@v3
      - name: Copy folder content recursively to remote
        uses: garygrossgarten/github-action-scp@v0.8.0
        with:
          local: ./bot.py
          remote: /home/mason/lyra/bot.py
          host: ${{ secrets.HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.PASSWORD }}
#         privateKey: ${{ secrets.PRIVATE_KEY}}
          rmRemote: true
      - name: stop bot service for replacement
        run: |
          sudo systemctl restart lyra
