on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout main for deployment
        uses: actions/checkout@v3
      - name: Copy bot.py to remote to deploy
        uses: garygrossgarten/github-action-scp@v0.8.0
        with:
          local: ./bot.py
          remote: /home/mason/lyra/bot.py
          host: ${{ secrets.HOST }}
          username: ${{ secrets.SSH_USER }}
          privateKey: ${{ secrets.PRIVATE_KEY}}
      - name: Restart the bot
        uses: fifsky/ssh-action@v0.0.6
        with:
          command: |
            sudo systemctl restart lyra
            exit 1
          host: ${{ secrets.HOST }}
          user: ${{ secrets.SSH_USER }}
          key: ${{ secrets.PRIVATE_KEY}}
          args: "-tt"
